menu:
  <>: /
  Archives: /archives
#  Lab: http://lab.bubkoo.com/
#  About: /about
#  Resume: /resume
  Github: https://github.com/bubkoo
#  Weibo: http://weibo.com/jeffreypee
#  RSS: /atom.xml

widgets:
#  - search
  - tagcloud
#  - category
  - recent_posts
#  - clock
#  - archive
#  - recent_comments
#  - recent_visitors

recent_posts_count: 10

blogrolls:
  - Heroic Yang's Blog: http://heroicyang.com/

duoshuo: bubkoo
baidu_analysis: 49a1665c33b011585a2a629fdbed5b61
google_analytics: UA-78428859-2
rss: true
